### ISSUE TITLE
Alterar escopo de Documentos Relacionados para exibir documentos relacionados com base nos últimos documentos acessados/visualizados

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/plat-serv-bvs#68]

**Comment by wilsonmoura** [comment]
O serviço Documentos Relacionados foi descontinuado. Por conseguinte, implementamos o recurso **Similares** como uma das ações disponíveis em cada registro da lista de documentos nos serviços:

- Documentos Favoritos
- Temas de Interesse
- Minhas Publicações

![screenshot-platserv2 teste bvsalud org-2019 01 09-14-16-40](https://user-images.githubusercontent.com/3779520/50912478-64d61380-1419-11e9-8577-eb0cbd51e064.png)

**Comment by renatomurasaki** [comment]
Esta issue pode se transformar em algo relacionado a oferecer documentos similares ao padrão de leitura/acesso do usuário.
________________________________
De: Wilson da Silva Moura <notifications@github.com>
Enviado: quarta-feira, 9 de janeiro de 2019 14:50:25
Para: bireme/plat-serv-bvs
Cc: Subscribed
Assunto: Re: [bireme/plat-serv-bvs] Alterar escopo de Documentos Relacionados para exibir documentos relacionados com base nos últimos documentos acessados/visualizados (#68)


Closed #68<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fplat-serv-bvs%2Fissues%2F68&data=02%7C01%7Cmurasaki%40paho.org%7Cea0146f0f834434ed4ea08d676529281%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636826494360414493&sdata=6LHQpo4bDJrjPhbC%2B%2FxRjufXUkI0HJt%2BbiFkPMUgS5Y%3D&reserved=0>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fplat-serv-bvs%2Fissues%2F68%23event-2063546015&data=02%7C01%7Cmurasaki%40paho.org%7Cea0146f0f834434ed4ea08d676529281%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636826494360414493&sdata=LH%2B%2BuNPt3x1WpW%2FuLHvOxPAAFuF%2BkLMp41PrtVOdpoc%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABK16u1Ww3ZzcilWbkKMB1PB19BssajWks5vBh3RgaJpZM4NcwJs&data=02%7C01%7Cmurasaki%40paho.org%7Cea0146f0f834434ed4ea08d676529281%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C636826494360414493&sdata=mCcJL5Lx5rVtyfu9749D%2BPJuu6A7j%2BpSCZ9uwfbejrE%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by wilsonmoura** [comment]
Issue reaberta para análise de uma possível implementação via widget no Dashboard.
